name: CI
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: 2.5
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.5
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.5
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: 2.5
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: 2.6
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-5.2.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: '3.0'
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 3.1
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-6.0.x"
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-6.0.x.sprockets-4.x"
          - ruby: 3.2
            gemfile: "gemfiles/Gemfile.rails-6.1.x.sprockets-4.x"
          - ruby: 2.7
            gemfile: Gemfile
          - ruby: '3.0'
            gemfile: Gemfile
          - ruby: '3.1'
            gemfile: Gemfile
          - ruby: 3.2
            gemfile: Gemfile
          - ruby: head
            gemfile: Gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
        continue-on-error: ${{ matrix.gemfile == 'Gemfile' }}
